@echo off
echo Running Cypress tests...
echo Running Login tests...
npx cypress run --spec cypress/e2e/loginTest.cy.js
echo Running  Add to Cart tests...
npx cypress run --spec cypress/e2e/addCart.cy.js
echo Running  Checkout tests...
npx cypress run --spec cypress/e2e/return.Chekout.cy.js

echo Tests completed!
pause
